# Generated by Django 4.1 on 2022-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
